# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: 'npm'
    directories: ['/frontend', '/backend']
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    commit-message:
      prefix: 'chore:'
    # メジャーバージョンのアップデートを無視
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
