version: '3'
name: blog
volumes:
  db:
services:
  db:
    image: postgres:16
    container_name: db
    volumes:
      - db:/var/lib/postgresql/blog_db_dev/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
