query PostIndexPage($category: [String!], $page: Int, $postsPerPage: Int) {
  posts(category: $category, page: $page, postsPerPage: $postsPerPage) {
    id
    title
    category
    publishDate
  }
}
