query GetPosts($category: [String!], $page: Int, $postsPerPage: Int) {
  getPosts(category: $category, page: $page, postsPerPage: $postsPerPage) {
    totalCount
    posts {
      id
      title
      category
      publishDate
    }
  }
}
